name: Build and Release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Set up environment variables
      - name: Set up production environment
        run: |
          echo "VITE_API_BASE_URL=https://kbs-api.onrender.com" > .env.production
          echo "VITE_SECRET_KEY=${{ secrets.VITE_SECRET_KEY }}" >> .env.production

      # Build the app
      - name: Build the app
        env:
          VITE_SECRET_KEY: ${{ secrets.VITE_SECRET_KEY }}
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true